version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.19
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-helm-cci-{{ checksum "helm.cabal" }}
      - run:
          name: Update machine
          command: sudo apt-get update
      - run:
          name: Install tools
          command: sudo apt-get install libsdl2-dev libcairo2-dev libpango1.0-de 
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Install gtk2hs-buildtools
          command: stack install gtk2hs-buildtools
      - run:
          name: Build and test 
          command: stack build --test --only-dependencies
      - save_cache:
          name: Cache Dependencies
          key: haskell-helm-cci-{{ checksum "helm.cabal" }}
          paths:
            - ".stack-work"
#      - store_artifacts: # upload build artifact for display in CircleCI
#          path: ~/.local/bin/circleci-demo-haskell-exe
#          destination: circleci-demo-haskell-exe


#    - sudo apt-get update
#    - sudo apt-get install libsdl2-dev libcairo2-dev libpango1.0-de stack
#
#  override:
#    - stack setup
#    - stack install gtk2hs-buildtools
#    - stack build --test --only-dependencies

