name:                flappy
version:             0.1.0.0
github:              "githubuser/flappy"
license:            MIT 
author: "Zack Corr"
maintainer: "Zack Corr <zack@z0w0.me>"
copyright: "(c) 2013-2017, Zack Corr"
category: "Game Engine. FRP"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flappy#readme>

dependencies:
- base >= 4.7 && < 5

data-files: images/*.png

library:
  source-dirs: src

executables:
  flappy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flappy

tests:
  flappy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flappy
